# Generated by Django 5.0.4 on 2024-10-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_role_remove_user_role_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
    ]
