# Generated by Django 5.0.4 on 2024-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
