# Generated by Django 5.0.4 on 2024-10-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='tag_id',
            new_name='code',
        ),
    ]
