# Generated by Django 5.0.4 on 2024-11-02 15:27

import django.utils.timezone
import imagekit.models.fields
import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_tag_id_rider_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rider',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=system.models.rider_image_path),
        ),
        migrations.AddField(
            model_name='rider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
