# Generated by Django 5.0.4 on 2024-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rider_created_at_rider_image_rider_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistancePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Distance Pricing',
                'verbose_name_plural': 'Distance Pricing',
            },
        ),
    ]
