# Generated by Django 5.0.4 on 2024-11-04 13:06

import django.db.models.deletion
import imagekit.models.fields
import system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_distancepricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(help_text='The address where the package should be picked up')),
                ('delivery_address', models.TextField(help_text='The address where the package should be delivered')),
                ('package_description', models.TextField(help_text='A description of the package to be delivered')),
                ('estimated_distance_km', models.FloatField(help_text='Estimated distance of the delivery in kilometers')),
                ('estimated_delivery_time', models.DateTimeField(help_text='The estimated time for the package to be delivered')),
                ('value_of_product', models.DecimalField(decimal_places=2, help_text='The value of the product being delivered in RWF', max_digits=10)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, help_text='The calculated price for the delivery in RWF', max_digits=10, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='An optional image of the package', null=True, upload_to=system.models.delivery_request_image_path)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='The current status of the delivery request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the request was last updated')),
                ('client', models.ForeignKey(help_text='The client who requested the delivery', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Request',
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
