# Generated by Django 5.0.4 on 2024-11-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_deliveryrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Unavailable', 'Unavailable')], default='Available', help_text='Current status of the rider', max_length=20)),
                ('last_assigned_at', models.DateTimeField(blank=True, help_text='The last time the rider was assigned a delivery', null=True)),
                ('delivery_request', models.OneToOneField(blank=True, help_text='The delivery request currently assigned to the rider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_assignment', to='system.deliveryrequest')),
                ('rider', models.OneToOneField(help_text='The rider assigned to deliveries', on_delete=django.db.models.deletion.CASCADE, related_name='rider_delivery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Delivery',
                'verbose_name_plural': 'Rider Deliveries',
            },
        ),
    ]
