# Generated by Django 5.0.4 on 2024-11-04 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_riderdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delete_status',
            field=models.BooleanField(default=False, help_text='Indicates if the delivery request has been deleted'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who deleted the delivery request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
