# Generated by Django 5.0.4 on 2024-11-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_deliveryrequest_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdelivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the rider was assigned to a delivery', null=True),
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the delivery was completed', null=True),
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the delivery started', null=True),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='rider',
            field=models.OneToOneField(help_text='The rider assigned to deliveries', on_delete=django.db.models.deletion.CASCADE, related_name='rider_delivery', to='system.rider'),
        ),
    ]
