# Generated by Django 5.0.4 on 2024-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_riderdelivery_assigned_at_riderdelivery_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='package_name',
            field=models.CharField(blank=True, help_text='Name of the package being delivered', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='payment_type',
            field=models.CharField(blank=True, help_text='The payment method for this delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Name of the recipient', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Phone number of the recipient', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='The address where the package should be delivered', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, help_text='The estimated time for the package to be delivered', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='estimated_distance_km',
            field=models.FloatField(blank=True, help_text='Estimated distance of the delivery in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='package_description',
            field=models.TextField(blank=True, help_text='A description of the package to be delivered', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='The address where the package should be picked up', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='value_of_product',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The value of the product being delivered in RWF', max_digits=10, null=True),
        ),
    ]
