# Generated by Django 5.0.4 on 2024-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_deliveryrequest_package_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, help_text='The estimated time for the package to be delivered', max_length=15, null=True),
        ),
    ]
