# Generated by Django 5.0.4 on 2024-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_deliveryrequest_estimated_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the delivery location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the delivery location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the pickup location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the pickup location', max_digits=9, null=True),
        ),
    ]
