# Generated by Django 5.0.4 on 2024-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_deliveryrequest_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_lat',
            field=models.CharField(blank=True, help_text='Latitude of the delivery location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_lng',
            field=models.CharField(blank=True, help_text='Longitude of the delivery location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_lat',
            field=models.CharField(blank=True, help_text='Latitude of the pickup location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_lng',
            field=models.CharField(blank=True, help_text='Longitude of the pickup location', max_length=100, null=True),
        ),
    ]
