# Generated by Django 5.0.4 on 2024-11-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_deliveryrequest_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_price',
            field=models.CharField(blank=True, help_text='The calculated price for the delivery in RWF', max_length=100, null=True),
        ),
    ]
