# Generated by Django 5.0.4 on 2024-11-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_deliveryrequest_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderdelivery',
            options={},
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='current_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='delivery_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_assignments', to='system.deliveryrequest'),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderdelivery',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_deliveries', to='system.rider'),
        ),
    ]
