# Generated by Django 5.0.4 on 2024-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alter_riderdelivery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderdelivery',
            name='current_status',
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Indicates whether the delivery has been completed'),
        ),
    ]
