# Generated by Django 5.0.4 on 2024-11-21 09:02

import imagekit.models.fields
import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_riderdelivery_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='permit_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=system.models.rider_image_path),
        ),
        migrations.AddField(
            model_name='rider',
            name='plate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
