# Generated by Django 5.0.4 on 2024-11-27 07:39

import imagekit.models.fields
import system.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_rider_insurance_rider_permit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='permit_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=system.models.rider_permit_image_path),
        ),
    ]
