# Generated by Django 5.0 on 2025-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_deliveryrequest_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', help_text='Status of the payment', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Unique transaction reference from Flutterwave', max_length=255, null=True, unique=True),
        ),
    ]
