# Generated by Django 5.0 on 2025-01-10 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_deliveryrequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookriderassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookriderassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
