# Generated by Django 5.0 on 2025-01-17 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_bookriderassignment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='commissioner',
            field=models.ForeignKey(blank=True, help_text='Optional: The commission agent for this rider.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioner_riders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Link to the rider's User account.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
