# Generated by Django 5.0 on 2025-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_rider_commissioner_rider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
