# Generated by Django 5.0 on 2025-01-17 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_rider_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='boss',
            field=models.ForeignKey(blank=True, help_text='Optional: The boss agent for this rider.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_riders', to=settings.AUTH_USER_MODEL),
        ),
    ]
