# Generated by Django 5.0 on 2025-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_remove_transactionhistory_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookriderassignment',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Indicates whether the delivery has been completed'),
        ),
    ]
