# Generated by Django 5.0 on 2025-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_bookriderassignment_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookriderassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the assignment', max_length=20),
        ),
    ]
