# Generated by Django 5.0 on 2025-01-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='requestdemo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request Demos', 'verbose_name_plural': 'Request Demos'},
        ),
        migrations.CreateModel(
            name='BookRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(blank=True, help_text='The address where the rider should pick up', null=True)),
                ('pickup_lat', models.CharField(blank=True, help_text='Latitude of the pickup location', max_length=100, null=True)),
                ('pickup_lng', models.CharField(blank=True, help_text='Longitude of the pickup location', max_length=100, null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='The address where the rider should deliver', null=True)),
                ('delivery_lat', models.CharField(blank=True, help_text='Latitude of the delivery location', max_length=100, null=True)),
                ('delivery_lng', models.CharField(blank=True, help_text='Longitude of the delivery location', max_length=100, null=True)),
                ('estimated_distance_km', models.CharField(blank=True, help_text='Estimated distance in kilometers', max_length=15, null=True)),
                ('estimated_delivery_time', models.CharField(blank=True, help_text='Estimated delivery time', max_length=15, null=True)),
                ('booking_price', models.CharField(blank=True, help_text='Calculated price for booking the rider in RWF', max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, help_text='Payment method for the booking', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the booking request', max_length=20)),
                ('delete_status', models.BooleanField(default=False, help_text='Indicates if the booking request has been deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the booking was last updated')),
                ('client', models.ForeignKey(help_text='The client who is booking the rider', on_delete=django.db.models.deletion.CASCADE, related_name='book_riders', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted the booking request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_book_riders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Rider',
                'verbose_name_plural': 'Book Riders',
                'ordering': ['-created_at'],
            },
        ),
    ]
