# Generated by Django 5.0 on 2025-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_contactus_contact_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrider',
            name='currency',
            field=models.CharField(default='RWF', help_text='Currency used in the transaction', max_length=10),
        ),
        migrations.AddField(
            model_name='bookrider',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', help_text='Current status of the payment', max_length=20),
        ),
        migrations.AddField(
            model_name='bookrider',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Transaction reference from Flutterwave', max_length=255, null=True, unique=True),
        ),
    ]
