# Generated by Django 5.0 on 2025-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_bookrider_currency_bookrider_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrider',
            name='mock_status',
            field=models.CharField(blank=True, help_text='Mock reference from Flutterwave', max_length=255, null=True, unique=True),
        ),
    ]
