# Generated by Django 5.0 on 2025-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bookrider_mock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrider',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bookrider',
            name='mock_status',
        ),
        migrations.AlterField(
            model_name='bookrider',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', help_text='Status of the payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookrider',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Unique transaction reference from Flutterwave', max_length=255, null=True, unique=True),
        ),
    ]
