# Generated by Django 5.0 on 2025-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_bookrider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrider',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the booking request', max_length=20),
        ),
    ]
