# Generated by Django 5.0 on 2025-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0026_remove_transactionhistory_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commissioner_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boss_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_transactions', to=settings.AUTH_USER_MODEL)),
                ('commissioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_transactions', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissioner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boss_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.deliveryrequest')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='transactions.transaction')),
            ],
        ),
    ]
