# Generated by Django 5.0 on 2025-01-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_remove_transactionhistory_transaction_and_more'),
        ('transactions', '0001_initial'),
        ('web', '0005_remove_bookrider_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='book_rider',
            field=models.ForeignKey(blank=True, help_text='Associated BookRider (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_histories', to='web.bookrider'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='delivery_request',
            field=models.ForeignKey(blank=True, help_text='Associated Delivery Request (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_histories', to='system.deliveryrequest'),
        ),
    ]
